# Generated by Django 4.0.6 on 2022-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Job_title', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Employment_type', models.CharField(choices=[('Complete', 'Complete'), ('Partial', 'Partial'), ('Internship', 'Internship')], max_length=100)),
                ('Wage', models.PositiveIntegerField(default=0)),
                ('Requirement', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
