# Generated by Django 5.0.2 on 2024-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('material', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField(max_length=100)),
            ],
        ),
    ]
